apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gradle-build
spec:
  workspaces:
    - name: output
  steps:
    - name: gradle-build
      image: gradle
      workingDir: /workspace/output
      command:
        - gradle
      args: 
        - build